{
  description = "Reflection adapter-zeroclaw — ZeroClaw agent runtime backend";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    agent-nix.url = "github:reflection-network/agent.nix";
  };

  outputs = { self, nixpkgs, flake-utils, agent-nix }:
    {
      lib.mkAgent = { agent }:
        let
          base = agent-nix.lib.mkAgent { inherit agent; };
        in
        flake-utils.lib.eachDefaultSystem (system:
          let
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfreePredicate = pkg:
                builtins.elem (nixpkgs.lib.getName pkg) [ "claude-code" ];
            };

            # ── ZeroClaw binary (prebuilt) ──────────────────────────
            version = "0.6.0";
            archMap = {
              x86_64-linux = {
                arch = "x86_64-unknown-linux-gnu";
                hash = "sha256-iqXPtp79/6j/o1LyzlA30mG0Ppg7lrYm/Cdz7a0l/xM=";
              };
              aarch64-linux = {
                arch = "aarch64-unknown-linux-gnu";
                hash = "sha256-QXJzj/v57ybp3dRO6yUbHYnXqOa2lJM4VQbtA5gFkLo=";
              };
              aarch64-darwin = {
                arch = "aarch64-apple-darwin";
                hash = "sha256-i4CM5CrueAfHzIGIih71LZKUHiXYDXeol+yHc/1jUGo=";
              };
            };
            archInfo = archMap.${system} or (throw "adapter-zeroclaw: unsupported system ${system}");

            zeroclaw-bin = pkgs.stdenv.mkDerivation {
              pname = "zeroclaw";
              inherit version;
              src = pkgs.fetchurl {
                url = "https://github.com/zeroclaw-labs/zeroclaw/releases/download/v${version}/zeroclaw-${archInfo.arch}.tar.gz";
                hash = archInfo.hash;
              };
              sourceRoot = ".";
              nativeBuildInputs = [ pkgs.autoPatchelfHook ];
              buildInputs = [ pkgs.stdenv.cc.cc.lib ];
              dontConfigure = true;
              dontBuild = true;
              installPhase = ''
                mkdir -p $out/bin
                cp zeroclaw $out/bin/zeroclaw
                chmod +x $out/bin/zeroclaw
              '';
            };

            # ── Agent config ────────────────────────────────────────
            provider = agent.provider or "anthropic";
            model = agent.model or "claude-sonnet-4-5-20250929";
            useClaudeCode = provider == "claude-code";

            telegramEnabled =
              (agent ? transports) &&
              (agent.transports ? telegram) &&
              (agent.transports.telegram.enable or false);
            telegramAllowedUsers =
              if agent ? transports &&
                 agent.transports ? telegram &&
                 agent.transports.telegram ? allowed-users
              then agent.transports.telegram.allowed-users
              else [];
            telegramMentionOnly =
              if agent ? transports &&
                 agent.transports ? telegram &&
                 agent.transports.telegram ? mention-only
              then agent.transports.telegram.mention-only
              else false;

            # Format list of strings as TOML array
            toTomlArray = xs:
              "[" + builtins.concatStringsSep ", " (map (x: ''"${x}"'') xs) + "]";

            # ── Generated config.toml ───────────────────────────────
            configToml = pkgs.writeText "config.toml" ''
              # Generated by adapter-zeroclaw for: ${agent.name}
              default_provider = "${provider}"
              default_model = "${model}"
              default_temperature = 0.7

              [agent]
              max_tool_iterations = 10
              max_history_messages = 50

              [channels_config]
              cli = false
              session_persistence = true
              session_backend = "sqlite"
              ${if telegramEnabled then ''

              [channels_config.telegram]
              allowed_users = ${toTomlArray telegramAllowedUsers}
              mention_only = ${if telegramMentionOnly then "true" else "false"}
              '' else ""}

              [memory]
              backend = "sqlite"
              auto_save = true

              [autonomy]
              level = "supervised"

              [gateway]
              port = 42617
              host = "0.0.0.0"
              allow_public_bind = true
              trust_forwarded_headers = true
              require_pairing = false

              [tunnel]
              provider = "custom"

              [tunnel.custom]
              start_command = "/etc/zeroclaw/tunnel-url.sh"
              url_pattern = "http"
            '';

            # ── Generated IDENTITY.md ───────────────────────────────
            identityMd = pkgs.writeText "IDENTITY.md" ''
              # ${agent.name}

              ${agent.system-prompt}
            '';

            tunnelUrlScript = pkgs.writeScript "tunnel-url.sh" ''
              #!${pkgs.bash}/bin/bash
              HOST="''${AGENT_HOSTNAME:-http://localhost:8080}"
              HOST="''${HOST%/}"
              echo "$HOST"
              exec ${pkgs.coreutils}/bin/sleep infinity
            '';

            # ── Config files bundle ─────────────────────────────────
            configFiles = pkgs.runCommand "zeroclaw-config" {} ''
              mkdir -p $out/etc/zeroclaw
              cp ${configToml} $out/etc/zeroclaw/config.toml
              cp ${identityMd} $out/etc/zeroclaw/IDENTITY.md
              cp ${tunnelUrlScript} $out/etc/zeroclaw/tunnel-url.sh
            '';

            # ── Runtime dependencies ────────────────────────────────
            runtimeDeps = [ zeroclaw-bin pkgs.coreutils pkgs.bash ]
              ++ pkgs.lib.optionals useClaudeCode [ pkgs.claude-code pkgs.curl pkgs.jq ];

            # ── Entrypoint ──────────────────────────────────────────
            entrypoint = pkgs.writeShellScript "entrypoint" ''
              set -euo pipefail

              export PATH="${pkgs.lib.makeBinPath runtimeDeps}:$PATH"

              WORKSPACE="$HOME/workspace"
              ZC_DIR="$HOME/.zeroclaw"

              mkdir -p "$WORKSPACE" "$ZC_DIR"
              ${if useClaudeCode then ''mkdir -p "$HOME/.claude"'' else ""}

              # Copy baked config to writable location (force-overwrite read-only copies from previous runs)
              install -m 644 /etc/zeroclaw/config.toml "$ZC_DIR/config.toml"
              install -m 644 /etc/zeroclaw/IDENTITY.md "$WORKSPACE/IDENTITY.md"

              # Inject runtime secrets into config
              ${if telegramEnabled then ''
              if [ -n "''${TELEGRAM_BOT_TOKEN:-}" ]; then
                ${pkgs.gnused}/bin/sed -i "s|\[channels_config\.telegram\]|[channels_config.telegram]\nbot_token = \"$TELEGRAM_BOT_TOKEN\"|" "$ZC_DIR/config.toml"
              else
                echo "WARNING: TELEGRAM_BOT_TOKEN not set, disabling telegram" >&2
                ${pkgs.gnused}/bin/sed -i '/\[channels_config\.telegram\]/,/^$/d' "$ZC_DIR/config.toml"
              fi
              '' else ""}

              ${if !useClaudeCode then ''
              if [ -n "''${API_KEY:-}" ]; then
                ${pkgs.gnused}/bin/sed -i "1i api_key = \"$API_KEY\"" "$ZC_DIR/config.toml"
              fi
              '' else ""}

              export ZEROCLAW_WORKSPACE="$WORKSPACE"

              ${web.startCmd}
              exec zeroclaw daemon
            '';

            # ── etc/passwd + etc/group ──────────────────────────────
            etcFiles = pkgs.runCommand "etc-files" {} ''
              mkdir -p $out/etc
              echo "root:x:0:0:root:/root:/bin/sh" > $out/etc/passwd
              echo "agent:x:1000:1000:Agent:/home/agent:/bin/bash" >> $out/etc/passwd
              echo "root:x:0:" > $out/etc/group
              echo "agent:x:1000:" >> $out/etc/group
            '';

            # ── Web (from agent.nix) ───────────────────────────────
            web = base.web.${system};

            gatewayProxyConf = pkgs.writeText "gateway.conf" ''
              location / {
                proxy_pass http://127.0.0.1:42617;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
              }
            '';

            gatewayConfDir = pkgs.runCommand "gateway-conf-dir" {} ''
              mkdir -p $out/etc/nginx/conf.d
              cp ${gatewayProxyConf} $out/etc/nginx/conf.d/gateway.conf
            '';

            imageName = builtins.replaceStrings [ " " ] [ "-" ]
              (pkgs.lib.toLower agent.name);
          in
          {
            devShells = base.devShells.${system} or {};

            packages.docker = pkgs.dockerTools.buildLayeredImage {
              name = imageName;
              tag = "latest";
              contents = [
                pkgs.bash
                pkgs.coreutils
                pkgs.cacert
                zeroclaw-bin
                etcFiles
                configFiles
                gatewayConfDir
              ] ++ web.packages
                ++ pkgs.lib.optionals useClaudeCode [
                pkgs.claude-code
                pkgs.curl
                pkgs.jq
              ];
              fakeRootCommands = ''
                mkdir -p home/agent/.zeroclaw home/agent/workspace tmp srv/www
                ${if useClaudeCode then "mkdir -p home/agent/.claude" else ""}
                chmod 1777 tmp
                chown -R 1000:1000 home/agent
              '';
              config = {
                User = "1000:1000";
                Env = [
                  "HOME=/home/agent"
                  "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt"
                ];
                WorkingDir = "/home/agent";
                Entrypoint = [ "${entrypoint}" ];
                ExposedPorts = { "${toString web.port}/tcp" = {}; };
              };
            };
          }
        );
    };
}
