{
  description = "Reflection adapter-zeroclaw — ZeroClaw agent runtime backend";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    agent-nix.url = "github:reflection-network/agent.nix";
  };

  outputs = { self, nixpkgs, flake-utils, agent-nix }:
    {
      lib.mkAgent = { agent }:
        let
          base = agent-nix.lib.mkAgent { inherit agent; };
        in
        flake-utils.lib.eachDefaultSystem (system:
          let
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfreePredicate = pkg:
                builtins.elem (nixpkgs.lib.getName pkg) [ "claude-code" ];
            };

            # ── ZeroClaw binary (prebuilt) ──────────────────────────
            version = "0.6.0";
            archMap = {
              x86_64-linux = {
                arch = "x86_64-unknown-linux-gnu";
                hash = "sha256-iqXPtp79/6j/o1LyzlA30mG0Ppg7lrYm/Cdz7a0l/xM=";
              };
              aarch64-linux = {
                arch = "aarch64-unknown-linux-gnu";
                hash = "sha256-QXJzj/v57ybp3dRO6yUbHYnXqOa2lJM4VQbtA5gFkLo=";
              };
              aarch64-darwin = {
                arch = "aarch64-apple-darwin";
                hash = "sha256-i4CM5CrueAfHzIGIih71LZKUHiXYDXeol+yHc/1jUGo=";
              };
            };
            archInfo = archMap.${system} or (throw "adapter-zeroclaw: unsupported system ${system}");

            zeroclaw-bin = pkgs.stdenv.mkDerivation {
              pname = "zeroclaw";
              inherit version;
              src = pkgs.fetchurl {
                url = "https://github.com/zeroclaw-labs/zeroclaw/releases/download/v${version}/zeroclaw-${archInfo.arch}.tar.gz";
                hash = archInfo.hash;
              };
              sourceRoot = ".";
              dontConfigure = true;
              dontBuild = true;
              installPhase = ''
                mkdir -p $out/bin
                cp zeroclaw $out/bin/zeroclaw
                chmod +x $out/bin/zeroclaw
              '';
            };

            # ── Agent config ────────────────────────────────────────
            provider = agent.provider or "anthropic";
            model = agent.model or "claude-sonnet-4-5-20250929";
            useClaudeCode = provider == "claude-code";

            telegramEnabled =
              (agent ? transports) &&
              (agent.transports ? telegram) &&
              (agent.transports.telegram.enable or false);
            telegramAllowedUsers =
              if agent ? transports &&
                 agent.transports ? telegram &&
                 agent.transports.telegram ? allowed-users
              then agent.transports.telegram.allowed-users
              else [];
            telegramMentionOnly =
              if agent ? transports &&
                 agent.transports ? telegram &&
                 agent.transports.telegram ? mention-only
              then agent.transports.telegram.mention-only
              else false;

            # Format list of strings as TOML array
            toTomlArray = xs:
              "[" + builtins.concatStringsSep ", " (map (x: ''"${x}"'') xs) + "]";

            # ── Generated config.toml ───────────────────────────────
            configToml = pkgs.writeText "config.toml" ''
              # Generated by adapter-zeroclaw for: ${agent.name}
              default_provider = "${provider}"
              default_model = "${model}"
              default_temperature = 0.7

              [agent]
              max_tool_iterations = 10
              max_history_messages = 50

              [channels_config]
              cli = false
              session_persistence = true
              session_backend = "sqlite"
              ${if telegramEnabled then ''

              [channels_config.telegram]
              allowed_users = ${toTomlArray telegramAllowedUsers}
              mention_only = ${if telegramMentionOnly then "true" else "false"}
              '' else ""}

              [memory]
              backend = "sqlite"
              auto_save = true

              [autonomy]
              level = "supervised"

              [gateway]
              port = 42617
              host = "0.0.0.0"
              allow_public_bind = true
            '';

            # ── Generated IDENTITY.md ───────────────────────────────
            identityMd = pkgs.writeText "IDENTITY.md" ''
              # ${agent.name}

              ${agent.system-prompt}
            '';

            # ── Config files bundle ─────────────────────────────────
            configFiles = pkgs.runCommand "zeroclaw-config" {} ''
              mkdir -p $out/etc/zeroclaw
              cp ${configToml} $out/etc/zeroclaw/config.toml
              cp ${identityMd} $out/etc/zeroclaw/IDENTITY.md
            '';

            # ── Runtime dependencies ────────────────────────────────
            runtimeDeps = [ zeroclaw-bin pkgs.coreutils pkgs.bash ]
              ++ pkgs.lib.optionals useClaudeCode [ pkgs.claude-code pkgs.curl pkgs.jq ];

            # ── Entrypoint ──────────────────────────────────────────
            entrypoint = pkgs.writeShellScript "entrypoint" ''
              set -euo pipefail

              export PATH="${pkgs.lib.makeBinPath runtimeDeps}:$PATH"

              WORKSPACE="$HOME/workspace"
              ZC_DIR="$HOME/.zeroclaw"

              mkdir -p "$WORKSPACE" "$ZC_DIR"
              ${if useClaudeCode then ''mkdir -p "$HOME/.claude"'' else ""}

              # Copy baked config and identity to writable locations
              cp /etc/zeroclaw/config.toml "$ZC_DIR/config.toml"
              cp /etc/zeroclaw/IDENTITY.md "$WORKSPACE/IDENTITY.md"

              export ZEROCLAW_WORKSPACE="$WORKSPACE"

              exec zeroclaw daemon
            '';

            # ── etc/passwd + etc/group ──────────────────────────────
            etcFiles = pkgs.runCommand "etc-files" {} ''
              mkdir -p $out/etc
              echo "root:x:0:0:root:/root:/bin/sh" > $out/etc/passwd
              echo "agent:x:1000:1000:Agent:/home/agent:/bin/bash" >> $out/etc/passwd
              echo "root:x:0:" > $out/etc/group
              echo "agent:x:1000:" >> $out/etc/group
            '';

            imageName = builtins.replaceStrings [ " " ] [ "-" ]
              (pkgs.lib.toLower agent.name);
          in
          {
            devShells = base.${system}.devShells or {};

            packages.docker = pkgs.dockerTools.buildLayeredImage {
              name = imageName;
              tag = "latest";
              contents = [
                pkgs.bash
                pkgs.coreutils
                pkgs.cacert
                zeroclaw-bin
                etcFiles
                configFiles
              ] ++ pkgs.lib.optionals useClaudeCode [
                pkgs.claude-code
                pkgs.curl
                pkgs.jq
              ];
              fakeRootCommands = ''
                mkdir -p home/agent/.zeroclaw home/agent/workspace tmp
                ${if useClaudeCode then "mkdir -p home/agent/.claude" else ""}
                chmod 1777 tmp
                chown -R 1000:1000 home/agent
              '';
              config = {
                User = "1000:1000";
                Env = [
                  "HOME=/home/agent"
                  "SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt"
                ];
                WorkingDir = "/home/agent";
                Entrypoint = [ "${entrypoint}" ];
              };
            };
          }
        );
    };
}
